# conda env create -f environment.yml
name: mlenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - seaborn
  - matplotlib
  - pandas
  - scikit-learn
  - notebook
  - black
  
#  - pip:
#    - Flask-Testing